import importAsDocumentColors from './import-document-colors'
import exportDocumentColors from './export-document-colors'
import setMetadata from './set-metadata'
import importPalette from './import-palette'
import exportPalette from './export-palette'
import linkArtboard from './link-artboard'
import { identifyAll, identifyFill, identifyBorder, identifyText } from './identify-colors'
import setColor from './set-color'
import updateColors from './update-colors'
import swapColor from './swap-color'
import swapTheme from './swap-theme'
import settings from './settings'
import showInfo from './show-info'
import openApp from './open-app'

export { importAsDocumentColors, setMetadata, importPalette, exportDocumentColors, exportPalette, linkArtboard, identifyAll, identifyFill, identifyBorder, identifyText, setColor, updateColors, swapColor, swapTheme, settings, showInfo, openApp }
